"""
VHC Talent OS — Talent Graph Service (Phase 1+2)

Builds + queries semantic embeddings of candidate profiles for:
  • "Find similar candidates" (candidate-to-candidate similarity)
  • Semantic search ("ML engineer with fintech exp in Bangalore")
  • Job ↔ candidate auto-matching

Design choices:
  • Embeddings stored in dedicated `candidate_embeddings` collection
    (cleaner than bloating candidate_bank with a 384-dim vector per row)
  • Local sentence-transformer model (BGE-small) — free, CPU-only, 80MB
  • MongoDB Atlas Vector Search compatible (drop-in switch in Phase 4-6)
  • Lazy single-instance model load — survives gunicorn worker restarts

The 3-line summary is generated by Qwen 14B on RunPod (free)
and stored alongside the embedding.
"""
from __future__ import annotations
import asyncio
import logging
import os
import time
from datetime import datetime, timezone
from typing import Any, Dict, List, Optional, Tuple

logger = logging.getLogger(__name__)

# ── Embedding model (lazy-loaded, single instance per process) ────────────────
# BGE-small-en-v1.5 — 384-dim, ~80 MB on disk, ~50 ms per encode on CPU
_EMBED_MODEL = None
_EMBED_MODEL_NAME = os.environ.get(
    "EMBEDDING_MODEL", "BAAI/bge-small-en-v1.5"
)
EMBED_DIM = 384


def _get_embed_model():
    """Lazy-load and cache the sentence-transformer model.
    First call takes ~3s (download + load); subsequent calls reuse it.
    """
    global _EMBED_MODEL
    if _EMBED_MODEL is not None:
        return _EMBED_MODEL
    try:
        from sentence_transformers import SentenceTransformer
        logger.info(f"[TalentGraph] Loading embedding model: {_EMBED_MODEL_NAME}")
        t0 = time.time()
        _EMBED_MODEL = SentenceTransformer(_EMBED_MODEL_NAME, device="cpu")
        logger.info(f"[TalentGraph] Model ready in {time.time() - t0:.1f}s")
        return _EMBED_MODEL
    except Exception as e:
        logger.error(f"[TalentGraph] Failed to load model: {e}")
        _EMBED_MODEL = False  # sentinel so we don't retry every call
        return None


# ──────────────────────────────────────────────────────────────────────────────
# Public API
# ──────────────────────────────────────────────────────────────────────────────

def embed_text(text: str) -> Optional[List[float]]:
    """Encode a single string → 384-d vector. Returns None on failure.

    Phase 54.16 (2026-05-11) — tries the RunPod sidecar first (frees ~1 GB
    EC2 RAM by removing the local sentence-transformers model). Falls back
    to local model if the sidecar is unreachable.
    """
    if not text or not text.strip():
        return None

    # Remote path (preferred — unloads BGE from EC2 RAM)
    try:
        from services.embed_client import embed_remote, is_remote_enabled
        if is_remote_enabled():
            vecs = embed_remote([text])
            if vecs is not None and vecs and vecs[0] is not None:
                return vecs[0]
    except Exception as e:
        logger.debug(f"[TalentGraph] remote embed_text issue: {e}")

    # Local fallback (legacy path — kept until BGE is fully decommissioned)
    model = _get_embed_model()
    if not model:
        return None
    try:
        text = text.strip()[:2000]
        vec = model.encode(text, normalize_embeddings=True, show_progress_bar=False)
        return vec.tolist()
    except Exception as e:
        logger.error(f"[TalentGraph] embed_text local failed: {e}")
        return None


def embed_texts_batch(texts: List[str]) -> List[Optional[List[float]]]:
    """Batch-encode for the backfill script. Much faster than one-by-one.

    Phase 54.16 — sidecar-first. Local fallback only if sidecar disabled
    or fails.
    """
    # Remote path
    try:
        from services.embed_client import embed_remote, is_remote_enabled
        if is_remote_enabled():
            vecs = embed_remote([(t or "")[:2000] for t in texts])
            if vecs is not None:
                return vecs
    except Exception as e:
        logger.debug(f"[TalentGraph] remote embed_texts_batch issue: {e}")

    # Local fallback
    model = _get_embed_model()
    if not model:
        return [None] * len(texts)
    try:
        cleaned = [(t or "").strip()[:2000] for t in texts]
        vecs = model.encode(
            cleaned, normalize_embeddings=True, show_progress_bar=False, batch_size=32
        )
        return [v.tolist() for v in vecs]
    except Exception as e:
        logger.error(f"[TalentGraph] embed_texts_batch local failed: {e}")
        return [None] * len(texts)


def build_candidate_text(candidate: Dict[str, Any]) -> str:
    """Compose the canonical text we want to embed for each candidate.
    Order matters: most-distinctive fields first so they dominate the vector.
    """
    parts = []

    if candidate.get("current_designation"):
        parts.append(f"Role: {candidate['current_designation']}")
    if candidate.get("current_employer") or candidate.get("current_company"):
        parts.append(
            f"Company: {candidate.get('current_employer') or candidate.get('current_company')}"
        )

    skills = candidate.get("key_skills") or candidate.get("skills") or []
    if isinstance(skills, list) and skills:
        parts.append("Skills: " + ", ".join(skills[:30]))

    yrs = candidate.get("experience_years") or candidate.get("total_experience_years")
    if yrs:
        parts.append(f"Experience: {yrs} years")

    if candidate.get("highest_qualification"):
        parts.append(f"Qualification: {candidate['highest_qualification']}")

    loc = candidate.get("current_location") or candidate.get("location")
    if loc:
        parts.append(f"Location: {loc}")

    if candidate.get("current_industry"):
        parts.append(f"Industry: {candidate['current_industry']}")

    # Compact work history (most recent 3 roles)
    work = candidate.get("work_experience") or []
    if isinstance(work, list) and work:
        roles = []
        for w in work[:3]:
            if isinstance(w, dict):
                d = w.get("designation") or w.get("title") or ""
                c = w.get("company") or w.get("employer") or ""
                if d or c:
                    roles.append(f"{d} at {c}".strip())
        if roles:
            parts.append("History: " + " | ".join(roles))

    if candidate.get("profile_summary"):
        parts.append(f"Summary: {candidate['profile_summary'][:500]}")

    return ". ".join(parts).strip()


def build_job_text(job: Dict[str, Any]) -> str:
    """Compose the canonical text for embedding a job. Used by job↔candidate matching."""
    parts = []
    if job.get("title") or job.get("job_title"):
        parts.append(f"Role: {job.get('title') or job.get('job_title')}")
    if job.get("required_skills") or job.get("skills"):
        sk = job.get("required_skills") or job.get("skills") or []
        if isinstance(sk, list):
            parts.append("Skills: " + ", ".join(sk[:30]))
    if job.get("min_experience") or job.get("max_experience"):
        parts.append(
            f"Experience: {job.get('min_experience', 0)}-{job.get('max_experience', '?')} years"
        )
    if job.get("location"):
        parts.append(f"Location: {job['location']}")
    if job.get("description"):
        parts.append(f"Description: {job['description'][:1500]}")
    return ". ".join(parts).strip()


# ──────────────────────────────────────────────────────────────────────────────
# Summary generation (Qwen 14B → free)
# ──────────────────────────────────────────────────────────────────────────────

async def generate_candidate_summary(candidate: Dict[str, Any]) -> Optional[str]:
    """Generate a 3-line TL;DR via Qwen 14B on RunPod. Returns None on failure
    (caller falls back to a simple rule-based summary).
    """
    raw_text = (
        candidate.get("raw_text_for_enrichment")
        or candidate.get("raw_page_text")
        or build_candidate_text(candidate)
    )
    if not raw_text or len(raw_text) < 100:
        return None

    system_prompt = (
        "You are a recruiting analyst. Write a crisp 3-line summary of the "
        "candidate that highlights: (1) their senior-most role and tenure, "
        "(2) their distinctive skill or domain edge, and (3) why a recruiter "
        "should care (e.g. niche stack, leadership, fast progression). "
        "No buzzwords, no fluff. Each line ≤ 25 words. Output the 3 lines only — "
        "no headings, no bullets, no preamble."
    )
    user_prompt = f"Candidate raw profile:\n\n{raw_text[:4000]}\n\nWrite the 3-line summary:"

    try:
        from services.llm_fallback_service import _call_runpod_vllm
        resp = await _call_runpod_vllm(system_prompt, user_prompt, temperature=0.2, text_mode=True)
        if not resp or not resp.get("content"):
            return None
        summary = resp["content"].strip()
        # Strip code-fences if Qwen wrapped it
        if summary.startswith("```"):
            summary = summary.strip("`").strip()
        # Quality gate: reject truncated / non-textual responses (e.g. "[1]", "{}", etc.)
        if len(summary) < 60 or summary.count(" ") < 8:
            logger.warning(f"[TalentGraph] Qwen summary too short/junk: {summary[:80]!r}")
            return None
        # Cap at 600 chars (3 × ~200) so a runaway response can't bloat the DB
        return summary[:600]
    except Exception as e:
        logger.error(f"[TalentGraph] generate_candidate_summary failed: {e}")
        return None


def fallback_rule_summary(candidate: Dict[str, Any]) -> str:
    """Cheap rule-based 3-liner used when Qwen is unavailable."""
    role = candidate.get("current_designation") or "Professional"
    company = (
        candidate.get("current_employer")
        or candidate.get("current_company")
        or "—"
    )
    yrs = (
        candidate.get("experience_years")
        or candidate.get("total_experience_years")
        or "?"
    )
    skills = candidate.get("key_skills") or candidate.get("skills") or []
    top_skills = ", ".join(skills[:5]) if isinstance(skills, list) else str(skills)[:80]
    loc = candidate.get("current_location") or candidate.get("location") or "—"
    notice = candidate.get("notice_period") or "—"

    line1 = f"{role} at {company} with {yrs} years experience."
    line2 = f"Key skills: {top_skills or '—'}." if top_skills else "Skill profile pending."
    line3 = f"Based in {loc}. Notice: {notice}."
    return "\n".join([line1, line2, line3])


# ──────────────────────────────────────────────────────────────────────────────
# Storage layer — `candidate_embeddings` collection
# ──────────────────────────────────────────────────────────────────────────────

EMBEDDINGS_COLL = "candidate_embeddings"


async def ensure_embeddings_indexes(db) -> None:
    """Create the indexes we need on `candidate_embeddings`. Safe to call on
    every boot — MongoDB skips already-existing indexes.
    Atlas Vector Search index is created via the Atlas UI; this stub leaves
    a hook for the standard B-tree indexes used by both UI and backfill.
    """
    coll = db[EMBEDDINGS_COLL]
    try:
        await coll.create_index("candidate_id", unique=True)
        await coll.create_index("updated_at")
        await coll.create_index("text_hash")
        logger.info("[TalentGraph] Indexes ensured on candidate_embeddings")
    except Exception as e:
        # Non-fatal — collection may not exist yet on first boot
        logger.warning(f"[TalentGraph] ensure_embeddings_indexes: {e}")


async def upsert_candidate_embedding(
    db,
    candidate: Dict[str, Any],
    *,
    summary: Optional[str] = None,
    force: bool = False,
) -> Dict[str, Any]:
    """Compute & upsert the embedding + summary for a single candidate.

    Args:
        candidate: Raw doc from candidate_bank (must contain `id`)
        summary: If provided, persist as-is. If None, generate via Qwen with
                 fallback to the rule-based summary.
        force: Re-embed even if text_hash matches the stored one

    Returns: {"status": "embedded|skipped|failed", "candidate_id": str}
    """
    cid = candidate.get("id")
    if not cid:
        return {"status": "failed", "reason": "no_candidate_id"}

    text = build_candidate_text(candidate)
    if not text or len(text) < 30:
        return {"status": "skipped", "candidate_id": cid, "reason": "insufficient_text"}

    text_hash = str(hash(text))
    if not force:
        existing = await db[EMBEDDINGS_COLL].find_one(
            {"candidate_id": cid, "text_hash": text_hash}, {"_id": 0, "text_hash": 1}
        )
        if existing:
            return {"status": "skipped", "candidate_id": cid, "reason": "unchanged"}

    # Run the CPU-bound encode off the asyncio loop
    vec = await asyncio.to_thread(embed_text, text)
    if vec is None:
        return {"status": "failed", "candidate_id": cid, "reason": "embedding_failed"}

    # Summary
    if summary is None:
        summary = await generate_candidate_summary(candidate)
        if not summary:
            summary = fallback_rule_summary(candidate)

    now_iso = datetime.now(timezone.utc).isoformat()
    doc = {
        "candidate_id": cid,
        "candidate_name": candidate.get("name"),
        "current_employer": candidate.get("current_employer") or candidate.get("current_company"),
        "current_designation": candidate.get("current_designation"),
        "experience_years": candidate.get("experience_years") or candidate.get("total_experience_years"),
        "current_location": candidate.get("current_location") or candidate.get("location"),
        "embedding": vec,
        "embedding_model": _EMBED_MODEL_NAME,
        "embedding_dim": EMBED_DIM,
        "text_hash": text_hash,
        "source_text": text[:2000],
        "summary": summary,
        "updated_at": now_iso,
    }
    await db[EMBEDDINGS_COLL].update_one(
        {"candidate_id": cid},
        {"$set": doc, "$setOnInsert": {"created_at": now_iso}},
        upsert=True,
    )

    # Mirror the summary back onto candidate_bank so the UI can show it
    # without an extra round-trip.
    await db.candidate_bank.update_one(
        {"id": cid},
        {"$set": {
            "ai_summary": summary,
            "ai_summary_at": now_iso,
            "embedding_indexed_at": now_iso,
        }},
    )
    return {"status": "embedded", "candidate_id": cid, "summary_chars": len(summary or "")}


# ──────────────────────────────────────────────────────────────────────────────
# Search helpers — used by the UI in Phase 4-6
# ──────────────────────────────────────────────────────────────────────────────

async def find_similar_candidates(
    db,
    candidate_id: str,
    limit: int = 10,
    min_score: float = 0.55,
) -> List[Dict[str, Any]]:
    """Return up to `limit` other candidates whose vectors are most similar.
    Uses cosine similarity (vectors are L2-normalized so dot-product == cosine).

    Strategy:
      • Fast path: MongoDB Atlas $vectorSearch (if index `candidate_vector_idx` exists)
      • Slow path: pull all vectors + numpy cosine in-process
    """
    seed = await db[EMBEDDINGS_COLL].find_one({"candidate_id": candidate_id}, {"_id": 0})
    if not seed or not seed.get("embedding"):
        return []
    seed_vec = seed["embedding"]

    # Try Atlas Vector Search first
    try:
        pipeline = [
            {
                "$vectorSearch": {
                    "index": "candidate_vector_idx",
                    "path": "embedding",
                    "queryVector": seed_vec,
                    "numCandidates": max(limit * 10, 100),
                    "limit": limit + 1,  # +1 because we'll filter out the seed itself
                }
            },
            {
                "$project": {
                    "_id": 0,
                    "candidate_id": 1,
                    "candidate_name": 1,
                    "current_employer": 1,
                    "current_designation": 1,
                    "experience_years": 1,
                    "current_location": 1,
                    "summary": 1,
                    "score": {"$meta": "vectorSearchScore"},
                }
            },
        ]
        results = await db[EMBEDDINGS_COLL].aggregate(pipeline).to_list(limit + 1)
        if results:
            return [
                r for r in results
                if r.get("candidate_id") != candidate_id and r.get("score", 0) >= min_score
            ][:limit]
    except Exception as e:
        logger.info(f"[TalentGraph] $vectorSearch unavailable, falling back: {e}")

    # Fallback: in-memory cosine
    return await _cosine_topk_fallback(db, seed_vec, exclude_id=candidate_id, limit=limit, min_score=min_score)


async def find_candidates_by_text(
    db,
    query: str,
    limit: int = 20,
    min_score: float = 0.40,
    routing_key: Optional[str] = None,
    timing: Optional[Dict[str, int]] = None,
    location_hint: Optional[str] = None,
) -> List[Dict[str, Any]]:
    """Free-form semantic search ('ML engineer with fintech in Bangalore').

    Optional ``timing`` dict — when passed, populated with per-step
    millisecond timings (`embed_ms`, `vector_search_ms`, `cosine_fallback_ms`,
    `rerank_ms`, `enrich_ms`). Lets the talent-search endpoint surface a
    latency breakdown to callers without a redeploy.

    Uses a hybrid score = 0.85·cosine + 0.15·keyword_overlap so that candidates
    whose source text actually mentions the query's discriminative keywords
    (location, industry, role tokens) rank above those that only match
    semantically. The displayed `score` remains pure cosine so scores stay
    comparable across queries.

    A/B (Phase 56.8, Jun 2026): when `routing_key` lands in the LTR
    bucket (env `LTR_AB_PCT`, default 10%), the rerank step uses the
    offline-trained XGBoost ranker. All other traffic continues on the
    cross-encoder (or hybrid fallback) path. Caller can inspect
    `results[0]["match_type"]` to know which arm ran ("ltr_xgboost",
    "cross_encoder", or "vector"/"hybrid" depending on fallback).

    FIX (Phase 55, 2026-02): only ~1.4% of `candidate_bank` has embeddings
    indexed, so a pure vector search misses ~98% of the talent pool. When the
    embedding pool returns fewer hits than requested, top up with a keyword +
    smart-tag fallback over the live `candidate_bank` so users never see an
    empty page just because the backfill hasn't caught up.
    """
    _t = time.time()
    qvec = await asyncio.to_thread(embed_text, query)
    if timing is not None: timing["embed_ms"] = int((time.time() - _t) * 1000)
    if not qvec:
        return await _keyword_fallback_search(db, query, limit)

    # Pull a wider pool than the user asked for so re-rank has room to work.
    fetch_limit = max(limit * 3, 60)

    _t = time.time()
    pool = None
    try:
        pipeline = [
            {
                "$vectorSearch": {
                    "index": "candidate_vector_idx",
                    "path": "embedding",
                    "queryVector": qvec,
                    "numCandidates": max(fetch_limit * 10, 200),
                    "limit": fetch_limit,
                }
            },
            {
                "$project": {
                    "_id": 0,
                    "candidate_id": 1,
                    "candidate_name": 1,
                    "current_employer": 1,
                    "current_designation": 1,
                    "experience_years": 1,
                    "current_location": 1,
                    "summary": 1,
                    "source_text": 1,
                    "score": {"$meta": "vectorSearchScore"},
                }
            },
        ]
        results = await db[EMBEDDINGS_COLL].aggregate(pipeline).to_list(fetch_limit)
        if results:
            pool = [r for r in results if r.get("score", 0) >= min_score]
    except Exception as e:
        logger.info(f"[TalentGraph] text-search via $vectorSearch unavailable: {e}")
    if timing is not None:
        timing["vector_search_ms"] = int((time.time() - _t) * 1000)
        timing["vector_search_hits"] = len(pool) if pool is not None else 0

    if pool is None:
        _t = time.time()
        pool = await _cosine_topk_fallback(
            db, qvec, exclude_id=None, limit=fetch_limit, min_score=min_score, with_text=True
        )
        if timing is not None:
            timing["cosine_fallback_ms"] = int((time.time() - _t) * 1000)
            timing["cosine_fallback_hits"] = len(pool)

    # ── Location seed (mandate-driven recall fix, Phase 55 / 2026-06-16) ──
    # The vector index covers only ~1.4% of `candidate_bank`. For a tight
    # mandate (e.g. Bangalore + 19-25L), the cluster-routed semantic pool
    # routinely returns 0 location-correct candidates — and the keyword
    # top-up at the bottom never fires because `len(pool) >= limit` from
    # other geographies. Seed the pool with a location-scoped DB scan so
    # the reranker (and the downstream strict filter) actually have
    # Bangalore candidates to work with.
    if location_hint and (location_hint or "").strip():
        _t = time.time()
        loc = location_hint.strip()
        # Indian city aliases (Bangalore↔Bengaluru, Bombay↔Mumbai, …).
        # Kept inline so this service stays standalone — same map exists in
        # routes/talent_search.py for the strict-filter intersection.
        _CITY_ALIASES = {
            "bangalore": ["bengaluru"], "bengaluru": ["bangalore"],
            "bombay": ["mumbai"],       "mumbai": ["bombay"],
            "calcutta": ["kolkata"],    "kolkata": ["calcutta"],
            "madras": ["chennai"],      "chennai": ["madras"],
            "gurgaon": ["gurugram"],    "gurugram": ["gurgaon"],
        }
        base = loc.lower()
        loc_terms = [base] + _CITY_ALIASES.get(base, [])
        seen_ids = {r.get("candidate_id") for r in (pool or []) if r.get("candidate_id")}
        # Token-scoped query so the seeder doesn't pull every Bangalore
        # candidate — only those that also share at least one query token.
        # Inject ALL location aliases so Bengaluru-stored candidates surface
        # for a Bangalore mandate (and vice-versa).
        seed_query = f"{' '.join(loc_terms)} {query}".strip()
        seed = await _keyword_fallback_search(
            db, seed_query, max(limit * 2, 40), exclude_ids=seen_ids
        )
        # Keep only seeds whose location actually matches the hint (or alias).
        # `_keyword_fallback_search` joins location with skills/employer/etc.
        # via $or, so a seed can come in from skill-match alone.
        seed = [
            s for s in seed
            if any(t in (str(s.get("current_location") or "")).lower() for t in loc_terms)
        ]
        # Track seed IDs so we can guarantee they're in the final result
        # set even if the reranker scores them low (no embedding/LTR features).
        location_seed_ids: set = set()
        if seed:
            for s in seed:
                s.setdefault("match_type", "location_seed")
                if s.get("candidate_id"):
                    location_seed_ids.add(s["candidate_id"])
            pool = (pool or []) + seed
        if timing is not None:
            timing["location_seed_ms"] = int((time.time() - _t) * 1000)
            timing["location_seed_hits"] = len(seed)
    else:
        location_seed_ids = set()

    # ── A/B rerank ──────────────────────────────────────────────────
    from services import ltr_service
    arm_ltr = ltr_service.should_use_ltr_arm(routing_key or query)

    _t = time.time()
    ranked = None
    if arm_ltr and pool:
        await _load_ltr_features(db, pool)
        ranked = ltr_service.rerank(pool, query, limit)
        if timing is not None: timing["rerank_arm"] = "ltr_xgboost"
    if ranked is None:
        # Default arm: cross-encoder (precision-boost) → hybrid fallback.
        ranked = (await asyncio.to_thread(_cross_encoder_rerank, pool, query, limit)) if pool else None
        if ranked is None:
            ranked = _hybrid_rerank(pool, query, limit)
            if timing is not None: timing["rerank_arm"] = "hybrid"
        else:
            if timing is not None: timing["rerank_arm"] = "cross_encoder"
    if timing is not None: timing["rerank_ms"] = int((time.time() - _t) * 1000)

    # Guarantee location seeds survive the rerank cull. A `_keyword_fallback_search`
    # candidate has no embedding (cosine=0) and no LTR features, so both arms
    # tend to push them to the bottom — even when the recruiter explicitly
    # filtered on that location. Re-inject any missing seeds so the strict
    # filter downstream has a chance to keep them.
    if location_seed_ids:
        ranked_ids = {r.get("candidate_id") for r in ranked if r.get("candidate_id")}
        missing = [s for s in (pool or []) if s.get("candidate_id") in (location_seed_ids - ranked_ids)]
        if missing:
            # Slot seeds at the END so they don't crowd out high-confidence
            # semantic hits — the strict filter (called by the route layer)
            # will reorder by relevance.
            ranked = ranked + missing
            if timing is not None:
                timing["location_seed_reinjected"] = len(missing)

    _t = time.time()
    await _enrich_with_candidate_bank(db, ranked)
    if timing is not None: timing["enrich_ms"] = int((time.time() - _t) * 1000)

    for r in ranked:
        r.setdefault("match_type", "vector")

    # Top-up with keyword fallback so users always see a usable list even
    # when embedding coverage is sparse.
    if len(ranked) < limit:
        _t = time.time()
        seen_ids = {r.get("candidate_id") for r in ranked if r.get("candidate_id")}
        needed   = limit - len(ranked)
        fallback = await _keyword_fallback_search(db, query, needed, exclude_ids=seen_ids)
        ranked.extend(fallback)
        if timing is not None: timing["keyword_topup_ms"] = int((time.time() - _t) * 1000)

    return ranked


async def _keyword_fallback_search(
    db,
    query: str,
    limit: int,
    exclude_ids: Optional[set] = None,
) -> List[Dict[str, Any]]:
    """Keyword + smart-tag fallback over `candidate_bank` when the embedding
    pool is sparse. Returns docs in the same shape as the vector search path
    so downstream code doesn't branch.
    """
    import re as _re_kw
    tokens = [t.strip() for t in _re_kw.findall(r"[A-Za-z0-9\.\+\#]{2,}", query) if t.strip()]
    # Drop very common stopwords so "with", "in", "the" don't dominate
    STOP = {"with", "and", "the", "for", "from", "in", "of", "to", "a", "an",
            "or", "at", "on", "by", "is", "be", "as", "into", "experience",
            "experienced", "senior", "junior", "lead"}
    tokens = [t for t in tokens if t.lower() not in STOP][:8]
    if not tokens:
        return []

    pat = "|".join(_re_kw.escape(t) for t in tokens)
    base_or = [
        {"smart_tags":  {"$regex": pat, "$options": "i"}},
        {"skills":      {"$regex": pat, "$options": "i"}},
        {"designation": {"$regex": pat, "$options": "i"}},
        {"headline":    {"$regex": pat, "$options": "i"}},
        {"current_employer": {"$regex": pat, "$options": "i"}},
        {"location":    {"$regex": pat, "$options": "i"}},
        {"industry":    {"$regex": pat, "$options": "i"}},
        {"summary":     {"$regex": pat, "$options": "i"}},
    ]
    q = {"$or": base_or}
    if exclude_ids:
        q = {"$and": [q, {"id": {"$nin": list(exclude_ids)}}]}

    docs = await db.candidate_bank.find(
        q,
        {
            "_id": 0, "id": 1, "name": 1,
            "designation": 1, "current_designation": 1, "headline": 1,
            "current_employer": 1, "current_company": 1,
            "location": 1, "current_location": 1,
            "experience_years": 1, "total_experience_years": 1,
            "skills": 1, "smart_tags": 1, "summary": 1,
        },
    ).sort("created_at", -1).limit(limit).to_list(limit)

    # Score = how many query tokens overlap with the document text
    out = []
    q_tokens_lower = {t.lower() for t in tokens}
    for d in docs:
        text = " ".join([
            str(d.get("designation") or d.get("current_designation") or ""),
            str(d.get("headline") or ""),
            str(d.get("current_employer") or d.get("current_company") or ""),
            str(d.get("location") or d.get("current_location") or ""),
            " ".join(d.get("skills") or []),
            " ".join(d.get("smart_tags") or []),
            str(d.get("summary") or "")[:500],
        ]).lower()
        hits = sum(1 for t in q_tokens_lower if t in text)
        score = hits / max(len(q_tokens_lower), 1)
        out.append({
            "candidate_id":  d.get("id"),
            "candidate_name": d.get("name"),
            "current_employer": d.get("current_employer") or d.get("current_company"),
            "current_designation": d.get("designation") or d.get("current_designation") or d.get("headline"),
            "current_location": d.get("location") or d.get("current_location"),
            "experience_years": d.get("experience_years") or d.get("total_experience_years"),
            "summary": d.get("summary"),
            "score": round(0.35 + 0.5 * score, 4),   # 0.35..0.85, clearly < pure vector hits
            "match_type": "keyword",
        })
    out.sort(key=lambda x: x["score"], reverse=True)
    return out


async def _enrich_with_candidate_bank(db, results: List[Dict[str, Any]]) -> None:
    """Fill in any null name/designation/employer/location fields from the live
    `candidate_bank` collection. The embedding snapshot was taken at indexing
    time, so it can be stale (e.g. early Naukri captures had null designations).
    Mutates `results` in-place.
    """
    if not results:
        return
    # Enrich any result missing ANY of the display/filter fields. The old
    # logic required ALL THREE to be missing — but Naukri embeddings often
    # carry the designation while `current_location` is empty (the field
    # name in candidate_bank is `location`, not `current_location`), so a
    # strict location filter would cull them before this hydration ran.
    needs = [
        r for r in results
        if not r.get("current_designation")
        or not r.get("current_employer")
        or not r.get("current_location")
        or r.get("experience_years") is None
    ]
    if not needs:
        return
    ids = [r["candidate_id"] for r in needs if r.get("candidate_id")]
    if not ids:
        return
    cursor = db.candidate_bank.find(
        {"id": {"$in": ids}},
        {
            "_id": 0, "id": 1, "name": 1,
            "current_designation": 1, "current_employer": 1, "current_company": 1,
            "current_location": 1, "location": 1,
            "total_experience_years": 1, "experience_years": 1,
            "headline": 1, "resume_headline": 1,
            "work_experience": 1,
        },
    )
    by_id = {d["id"]: d async for d in cursor}
    for r in results:
        c = by_id.get(r.get("candidate_id"))
        if not c:
            continue
        # Designation: live → most-recent work entry → headline (first 80 chars)
        designation = r.get("current_designation") or c.get("current_designation")
        if not designation:
            for w in (c.get("work_experience") or []):
                if isinstance(w, dict):
                    designation = w.get("designation") or w.get("title")
                    if designation:
                        break
        if not designation:
            headline = (c.get("resume_headline") or c.get("headline") or "").strip()
            if headline:
                designation = (headline[:80] + "…") if len(headline) > 80 else headline

        r["candidate_name"] = r.get("candidate_name") or c.get("name")
        r["current_designation"] = designation
        r["current_employer"] = (
            r.get("current_employer")
            or c.get("current_employer")
            or c.get("current_company")
        )
        r["current_location"] = (
            r.get("current_location") or c.get("current_location") or c.get("location")
        )
        r["experience_years"] = (
            r.get("experience_years")
            or c.get("experience_years")
            or c.get("total_experience_years")
        )


async def _load_ltr_features(db, results: List[Dict[str, Any]]) -> None:
    """Fetch the candidate fields the LTR ranker needs (skills, cluster_id,
    updated_at) onto each result in-place. Runs only on the A/B-selected
    arm so we don't pay this DB cost for cross-encoder / hybrid traffic.

    Only fetches for results that don't already carry the LTR fields,
    making this safe to call after a previous rerank.
    """
    if not results:
        return
    need_ids = [
        r["candidate_id"] for r in results
        if r.get("candidate_id") and "skills" not in r
    ]
    if not need_ids:
        return
    cursor = db.candidate_bank.find(
        {"id": {"$in": need_ids}},
        {"_id": 0, "id": 1, "skills": 1, "cluster_id": 1, "updated_at": 1, "created_at": 1},
    )
    by_id = {d["id"]: d async for d in cursor}
    for r in results:
        c = by_id.get(r.get("candidate_id"))
        if not c:
            continue
        r["skills"] = c.get("skills")
        r["cluster_id"] = c.get("cluster_id")
        r["updated_at"] = c.get("updated_at") or c.get("created_at")


# ──────────────────────────────────────────────────────────────────────────────
# Hybrid re-rank: cosine + lightweight keyword overlap
# ──────────────────────────────────────────────────────────────────────────────

# Words too common to discriminate one candidate from another
_STOPWORDS = frozenset({
    "and", "the", "for", "with", "who", "has", "have", "are", "any", "all",
    "looking", "candidate", "candidates", "experience", "experienced", "year",
    "years", "exp", "open", "work", "working", "role", "based", "from", "this",
    "that", "preferably", "preferred", "must", "should", "good", "great", "strong",
})

def _query_keywords(query: str) -> List[str]:
    import re
    tokens = re.findall(r"[a-zA-Z][a-zA-Z+\-\.]{2,}", (query or "").lower())
    out = []
    seen = set()
    for t in tokens:
        if t in _STOPWORDS or t in seen:
            continue
        seen.add(t)
        out.append(t)
    return out


def _cross_encoder_rerank(
    results: List[Dict[str, Any]],
    query: str,
    limit: int,
) -> Optional[List[Dict[str, Any]]]:
    """Optional precision pass using the BGE cross-encoder on the RunPod sidecar.

    Activated when env `CROSS_ENCODER_ENABLED=true` (default off, behind a
    feature flag). Only runs when there are ≥4 candidates and the sidecar
    is reachable. Falls back to None on any failure so the caller can use
    the cheaper bi-encoder rerank.

    The cross-encoder is a one-time ~5× precision boost on the *top of the
    cosine pool* — we limit the input batch to MAX_PAIRS to keep the
    request bounded (≤200ms even on cold GPU).
    """
    MAX_PAIRS = 64  # sidecar hard cap is 128; keep room for safety
    if os.environ.get("CROSS_ENCODER_ENABLED", "false").lower() not in ("1", "true", "yes"):
        return None
    if not results or len(results) < 4:
        return None
    try:
        from services.embed_client import rerank_remote, is_remote_enabled
        if not is_remote_enabled():
            return None
        # Build a compact doc string per candidate — same fields as
        # _hybrid_rerank haystack but joined with spaces.
        pool = results[:MAX_PAIRS]
        docs = []
        for r in pool:
            doc = " | ".join(filter(None, [
                (r.get("candidate_name") or "")[:80],
                (r.get("current_designation") or "")[:80],
                (r.get("current_employer") or "")[:80],
                (r.get("current_location") or "")[:60],
                (r.get("summary") or r.get("source_text") or "")[:600],
            ]))
            docs.append(doc.strip() or (r.get("candidate_name") or "n/a"))

        hits = rerank_remote(query=query[:400], documents=docs, top_k=limit)
        if not hits:
            return None
        # Re-order pool by sidecar score; expose score in result for the UI.
        idx_map = {h["index"]: float(h["score"]) for h in hits}
        for i, r in enumerate(pool):
            r["_rerank_score"] = idx_map.get(i, 0.0)
            r["match_type"] = "cross_encoder"
        pool.sort(key=lambda r: r.get("_rerank_score") or 0.0, reverse=True)
        for r in pool:
            r.pop("source_text", None)
        return pool[:limit]
    except Exception as e:  # noqa: BLE001
        logger.warning(f"[TalentGraph] cross-encoder rerank failed: {e!s} — falling back")
        return None


def _hybrid_rerank(
    results: List[Dict[str, Any]], query: str, limit: int
) -> List[Dict[str, Any]]:
    """Re-rank by 0.85·cosine + 0.15·keyword_overlap. Returns top-`limit`.

    Each result must already have `score` (cosine, 0-1) and ideally
    `source_text` for keyword matching. Falls back to designation/employer/
    location/summary when source_text is absent.
    """
    if not results:
        return []
    keywords = _query_keywords(query)
    if not keywords:
        # No discriminative tokens — keep pure cosine ranking
        results.sort(key=lambda r: r.get("score") or 0.0, reverse=True)
        return results[:limit]

    for r in results:
        haystack = " ".join([
            (r.get("source_text") or ""),
            (r.get("candidate_name") or ""),
            (r.get("current_designation") or ""),
            (r.get("current_employer") or ""),
            (r.get("current_location") or ""),
            (r.get("summary") or ""),
        ]).lower()
        if not haystack:
            r["_keyword_overlap"] = 0.0
            r["_combined_score"] = r.get("score") or 0.0
            continue
        hits = sum(1 for kw in keywords if kw in haystack)
        overlap = hits / max(len(keywords), 1)  # 0..1
        r["_keyword_overlap"] = round(overlap, 3)
        r["_combined_score"] = 0.85 * (r.get("score") or 0.0) + 0.15 * overlap

    results.sort(key=lambda r: r.get("_combined_score") or 0.0, reverse=True)
    # Drop the internal helper fields before returning to the API
    for r in results:
        r.pop("_combined_score", None)
        # keep _keyword_overlap visible — useful for the UI / future debugging
        r.pop("source_text", None)
    return results[:limit]


async def find_matching_candidates_for_job(
    db,
    job: Dict[str, Any],
    limit: int = 25,
    min_score: float = 0.45,
) -> List[Dict[str, Any]]:
    """Given a job doc, return semantically-matched candidates ranked by similarity.
    Caller can layer on hard filters (location, salary, notice) afterwards.
    """
    text = build_job_text(job)
    if not text:
        return []
    return await find_candidates_by_text(db, text, limit=limit, min_score=min_score)


# ──────────────────────────────────────────────────────────────────────────────
# Internal — bounded cosine fallback for environments without Atlas Vector Search
# ──────────────────────────────────────────────────────────────────────────────
# Phase 57 (Jun 2026) perf rewrite. The old fallback loaded EVERY embedding
# (133k docs, 400-700MB incl. summaries) into one global in-process matrix
# with a 5-minute TTL behind a single asyncio.Lock. On Atlas Flex (no
# $vectorSearch) every similar/match-job/search call after a TTL expiry or a
# gunicorn worker recycle re-downloaded the whole collection: 30-700s stalls,
# connection-pool exhaustion (AutoReconnect storms), repeated memory-recovery
# incidents, and portal-wide p99 of 40s+. This rewrite scans only the
# clusters nearest the query:
#   1. approximate cluster centroids (sample-mean of ~40 members, cached 6h)
#   2. per-cluster embedding matrices (cached 30 min, LRU-capped)
#   3. plus the newest not-yet-clustered embeddings (cached 5 min)
#   4. numpy scoring inside asyncio.to_thread — never blocks the event loop
#   5. display fields hydrated only for the final top-K ids
# Worst-case Atlas transfer per cold query: ~3 clusters × ~12MB vs 700MB.

_CENTROID_CACHE: Dict[str, Any] = {"loaded_at": 0.0, "centroids": []}
_CENTROID_TTL_S = 6 * 3600.0
_CENTROID_LOCK = asyncio.Lock()

_CLUSTER_MAT_CACHE: Dict[Any, Dict[str, Any]] = {}  # key -> {loaded_at, ttl, ids, mat}
_CLUSTER_MAT_TTL_S = 1800.0
_CLUSTER_MAT_MAX = 32          # LRU cap — covers all 25 clusters + unclustered + headroom
_CLUSTER_FETCH_LIMIT = 15000   # hard per-cluster bound
_TOP_CLUSTERS = 3              # clusters scanned per query

_UNCLUSTERED_KEY = "__unclustered__"
_UNCLUSTERED_TTL_S = 300.0     # fresh captures should appear fast
_UNCLUSTERED_LIMIT = 4000      # newest embeddings without a cluster_id yet


async def _get_centroids(db) -> List[Any]:
    """Approximate centroid per cluster: mean of ≤40 sampled member vectors.

    The clustering script stores centroids in PCA space (useless against raw
    query embeddings), so we derive original-space centroids cheaply here.
    Cached for hours — clusters only change when re-clustering runs.
    """
    import numpy as np

    async with _CENTROID_LOCK:
        now = time.time()
        if _CENTROID_CACHE["centroids"] and now - _CENTROID_CACHE["loaded_at"] < _CENTROID_TTL_S:
            return _CENTROID_CACHE["centroids"]

        cluster_ids = await db["candidate_clusters"].distinct("cluster_id")
        if not cluster_ids:
            _CENTROID_CACHE.update({"loaded_at": now, "centroids": []})
            return []

        async def _centroid(cid):
            docs = await db[EMBEDDINGS_COLL].aggregate([
                {"$match": {"cluster_id": cid}},
                {"$sample": {"size": 40}},
                {"$project": {"_id": 0, "embedding": 1}},
            ]).to_list(40)
            if not docs:
                return None
            m = np.array([d["embedding"] for d in docs], dtype=np.float32).mean(axis=0)
            norm = float(np.linalg.norm(m))
            return (cid, m / norm) if norm > 0 else None

        results = await asyncio.gather(*[_centroid(c) for c in cluster_ids])
        centroids = [r for r in results if r is not None]
        _CENTROID_CACHE.update({"loaded_at": now, "centroids": centroids})
        logger.info(f"[TalentGraph] Cluster centroids refreshed: {len(centroids)} clusters")
        return centroids


async def _get_cluster_block(db, key) -> Tuple[List[str], Any]:
    """(candidate_ids, numpy matrix) for one cluster — or the newest
    unclustered embeddings when key == _UNCLUSTERED_KEY. TTL + LRU cached."""
    import numpy as np

    now = time.time()
    entry = _CLUSTER_MAT_CACHE.get(key)
    if entry and now - entry["loaded_at"] < entry["ttl"]:
        return entry["ids"], entry["mat"]

    proj = {"_id": 0, "candidate_id": 1, "embedding": 1}
    if key == _UNCLUSTERED_KEY:
        # cluster_id: None matches docs where the field is missing OR null —
        # and it can still walk the cluster_id index.
        cur = (
            db[EMBEDDINGS_COLL]
            .find({"cluster_id": None}, proj)
            .sort("updated_at", -1)
            .limit(_UNCLUSTERED_LIMIT)
        )
        ttl = _UNCLUSTERED_TTL_S
        docs = await cur.to_list(_UNCLUSTERED_LIMIT)
    else:
        cur = db[EMBEDDINGS_COLL].find({"cluster_id": key}, proj).limit(_CLUSTER_FETCH_LIMIT)
        ttl = _CLUSTER_MAT_TTL_S
        docs = await cur.to_list(_CLUSTER_FETCH_LIMIT)

    ids = [d.get("candidate_id") for d in docs]
    mat = (
        np.array([d["embedding"] for d in docs], dtype=np.float32)
        if docs else np.zeros((0, 1), dtype=np.float32)
    )

    # LRU-ish eviction: drop the stalest entry when over cap
    if len(_CLUSTER_MAT_CACHE) >= _CLUSTER_MAT_MAX and key not in _CLUSTER_MAT_CACHE:
        oldest = min(_CLUSTER_MAT_CACHE, key=lambda k: _CLUSTER_MAT_CACHE[k]["loaded_at"])
        _CLUSTER_MAT_CACHE.pop(oldest, None)
    _CLUSTER_MAT_CACHE[key] = {"loaded_at": now, "ttl": ttl, "ids": ids, "mat": mat}
    return ids, mat


def invalidate_vector_cache() -> None:
    """Force the next search to reload from Mongo. Call after a backfill or
    re-clustering run if you want new vectors visible immediately."""
    _CENTROID_CACHE.update({"loaded_at": 0.0, "centroids": []})
    _CLUSTER_MAT_CACHE.clear()


async def prime_all_clusters(db) -> Dict[str, Any]:
    """Phase 1.5 boot warmup: fetch EVERY cluster block + the unclustered
    bucket into the in-process matrix cache so the cluster-routing
    fallback never pays a Mongo round-trip on the user-facing path.

    Returns a small dict summarising what was loaded — useful for the
    /api/talent/warmup endpoint response and for boot logs.

    Cost: ~5 s × N_clusters_in_parallel (typically 2-4 s wall-clock for
    25 clusters with motor's connection pool). RAM ≈ 7.7 MB per cluster
    block + ~12 MB unclustered ≈ 200 MB total for the 140k bank.
    """
    cluster_ids = await db["candidate_clusters"].distinct("cluster_id")
    keys = list(cluster_ids) + [_UNCLUSTERED_KEY]
    # Parallel fetch — motor's pool handles back-pressure
    try:
        await asyncio.gather(*[_get_cluster_block(db, k) for k in keys])
    except Exception as e:
        logger.warning(f"[TalentGraph] prime_all_clusters partial failure: {e}")
    loaded = len(_CLUSTER_MAT_CACHE)
    total_rows = sum(len(v["ids"]) for v in _CLUSTER_MAT_CACHE.values())
    logger.info(
        f"[TalentGraph] Cluster cache primed: {loaded} blocks, {total_rows:,} embeddings"
    )
    return {"blocks_loaded": loaded, "embeddings_in_cache": total_rows}


async def _cosine_topk_fallback(
    db,
    qvec: List[float],
    exclude_id: Optional[str],
    limit: int,
    min_score: float,
    with_text: bool = False,
) -> List[Dict[str, Any]]:
    try:
        import numpy as np
    except Exception:
        logger.warning("[TalentGraph] numpy missing — fallback unavailable")
        return []

    q = np.array(qvec, dtype=np.float32)

    # 1. Route the query to its nearest clusters (cheap: ≤25 dot products)
    centroids = await _get_centroids(db)
    chosen: List[Any] = []
    if centroids:
        ranked_clusters = sorted(
            ((float(np.dot(vec, q)), cid) for cid, vec in centroids), reverse=True
        )
        chosen = [cid for _, cid in ranked_clusters[:_TOP_CLUSTERS]]
    else:
        logger.warning(
            "[TalentGraph] No clusters found — fallback degraded to newest "
            f"{_UNCLUSTERED_LIMIT} embeddings only. Run cluster_candidates.py."
        )

    # 2. Fetch the chosen cluster blocks + the always-included fresh bucket
    blocks = await asyncio.gather(
        *[_get_cluster_block(db, key) for key in chosen + [_UNCLUSTERED_KEY]]
    )

    # 3. Score in a worker thread (event loop stays free)
    def _score() -> List[Tuple[str, float]]:
        out: List[Tuple[str, float]] = []
        seen: set = set()
        for ids, mat in blocks:
            if mat.shape[0] == 0:
                continue
            scores = mat @ q
            for i in np.argsort(scores)[::-1][: limit * 3]:
                s = float(scores[i])
                if s < min_score:
                    break
                cid = ids[i]
                if not cid or cid == exclude_id or cid in seen:
                    continue
                seen.add(cid)
                out.append((cid, s))
        out.sort(key=lambda x: x[1], reverse=True)
        return out[:limit]

    top = await asyncio.to_thread(_score)
    if not top:
        return []

    # 4. Hydrate display fields for the final top-K only
    proj = {
        "_id": 0, "candidate_id": 1, "candidate_name": 1,
        "current_employer": 1, "current_designation": 1,
        "experience_years": 1, "current_location": 1, "summary": 1,
    }
    if with_text:
        proj["source_text"] = 1
    docs = await db[EMBEDDINGS_COLL].find(
        {"candidate_id": {"$in": [cid for cid, _ in top]}}, proj
    ).to_list(len(top) * 2)
    by_id = {d.get("candidate_id"): d for d in docs}

    ranked: List[Dict[str, Any]] = []
    for cid, s in top:
        d = by_id.get(cid) or {}
        row = {
            "candidate_id": cid,
            "candidate_name": d.get("candidate_name"),
            "current_employer": d.get("current_employer"),
            "current_designation": d.get("current_designation"),
            "experience_years": d.get("experience_years"),
            "current_location": d.get("current_location"),
            "summary": d.get("summary"),
            "score": s,
        }
        if with_text:
            row["source_text"] = d.get("source_text")
        ranked.append(row)
    ranked.sort(key=lambda x: x["score"], reverse=True)
    return ranked[:limit]
